import { type Course, type User } from "@shared/schema";

export const mockCourses: Course[] = [
  {
    id: "1",
    title: "React Fundamentals",
    description: "Master React from basics to advanced concepts with hands-on projects",
    category: "Frontend",
    level: "beginner",
    duration: 12,
    thumbnail: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=200",
    mentorId: "mentor1",
    students: 1247,
    price: 9900,
    createdAt: new Date(),
  },
  {
    id: "2",
    title: "Python for Beginners",
    description: "Learn Python programming from scratch with practical examples",
    category: "Backend",
    level: "beginner",
    duration: 15,
    thumbnail: "https://images.unsplash.com/photo-1526379095098-d400fd0bf935?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=200",
    mentorId: "mentor2",
    students: 2156,
    price: 7900,
    createdAt: new Date(),
  },
  {
    id: "3",
    title: "Advanced JavaScript",
    description: "Deep dive into modern JavaScript features and best practices",
    category: "Frontend",
    level: "intermediate",
    duration: 18,
    thumbnail: "https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=200",
    mentorId: "mentor3",
    students: 987,
    price: 12900,
    createdAt: new Date(),
  },
  {
    id: "4",
    title: "Node.js & Express",
    description: "Build scalable backend applications with Node.js and Express",
    category: "Backend",
    level: "intermediate",
    duration: 20,
    thumbnail: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=200",
    mentorId: "mentor4",
    students: 1543,
    price: 14900,
    createdAt: new Date(),
  },
  {
    id: "5",
    title: "React Native Basics",
    description: "Create cross-platform mobile apps with React Native",
    category: "Mobile",
    level: "beginner",
    duration: 14,
    thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=200",
    mentorId: "mentor5",
    students: 823,
    price: 11900,
    createdAt: new Date(),
  },
  {
    id: "6",
    title: "Docker & Kubernetes",
    description: "Master containerization and orchestration for modern deployment",
    category: "DevOps",
    level: "advanced",
    duration: 25,
    thumbnail: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=200",
    mentorId: "mentor6",
    students: 456,
    price: 19900,
    createdAt: new Date(),
  },
  {
    id: "7",
    title: "Data Analysis with Python",
    description: "Learn pandas, numpy, and matplotlib for data analysis",
    category: "Data Science",
    level: "intermediate",
    duration: 16,
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=200",
    mentorId: "mentor7",
    students: 734,
    price: 13900,
    createdAt: new Date(),
  },
  {
    id: "8",
    title: "MERN Stack Mastery",
    description: "Complete web application development with MongoDB, Express, React, Node",
    category: "Full Stack",
    level: "advanced",
    duration: 35,
    thumbnail: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=200",
    mentorId: "mentor8",
    students: 612,
    price: 24900,
    createdAt: new Date(),
  },
];

export const mockMentors: User[] = [
  {
    id: "mentor1",
    username: "johnsmith",
    email: "john@example.com",
    password: "password",
    firstName: "John",
    lastName: "Smith",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&h=200",
    role: "mentor",
    bio: "Senior React Developer with 8 years of experience at Google",
    skills: ["React", "TypeScript", "Next.js"],
    experience: "8 years",
    company: "Google",
    createdAt: new Date(),
  },
  {
    id: "mentor2",
    username: "sarahjohnson",
    email: "sarah@example.com",
    password: "password",
    firstName: "Sarah",
    lastName: "Johnson",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&h=200",
    role: "mentor",
    bio: "Python Backend Expert with 10 years of experience at Microsoft",
    skills: ["Python", "Django", "AWS"],
    experience: "10 years",
    company: "Microsoft",
    createdAt: new Date(),
  },
  {
    id: "mentor3",
    username: "mikechen",
    email: "mike@example.com",
    password: "password",
    firstName: "Mike",
    lastName: "Chen",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&h=200",
    role: "mentor",
    bio: "Full Stack Architect with 12 years of experience at Meta",
    skills: ["JavaScript", "Node.js", "GraphQL"],
    experience: "12 years",
    company: "Meta",
    createdAt: new Date(),
  },
  {
    id: "mentor4",
    username: "davidwilson",
    email: "david@example.com",
    password: "password",
    firstName: "David",
    lastName: "Wilson",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&h=200",
    role: "mentor",
    bio: "Backend Architect specializing in Node.js and cloud technologies",
    skills: ["Node.js", "Express", "MongoDB"],
    experience: "9 years",
    company: "Netflix",
    createdAt: new Date(),
  },
  {
    id: "mentor5",
    username: "emilyrodriguez",
    email: "emily@example.com",
    password: "password",
    firstName: "Emily",
    lastName: "Rodriguez",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&h=200",
    role: "mentor",
    bio: "Mobile Tech Lead with expertise in React Native and iOS development",
    skills: ["React Native", "iOS", "Android"],
    experience: "7 years",
    company: "Uber",
    createdAt: new Date(),
  },
  {
    id: "mentor6",
    username: "alexkumar",
    email: "alex@example.com",
    password: "password",
    firstName: "Alex",
    lastName: "Kumar",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-4.0.3&auto=format&fit=crop&w=200&h=200",
    role: "mentor",
    bio: "DevOps Engineer with expertise in containerization and cloud infrastructure",
    skills: ["Docker", "Kubernetes", "AWS"],
    experience: "11 years",
    company: "Amazon",
    createdAt: new Date(),
  },
];
